# 100 numpy exercises

This is a collection of exercises that have perform.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

('1.23.5', <function numpy.__config__.show()>)

#### 3. Create a null vector of size 10 (★☆☆)

In [17]:
import numpy as np
vector1 = np.linspace(0,0,10)
vector1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [28]:
import numpy as np

def get_numpy_array_size(arr):
  return arr.size * arr.itemsize

# Example usage:
my_array = np.array([1, 2, 3, 4, 5])
memory_size = get_numpy_array_size(my_array)
print("Memory size of the NumPy array:", memory_size, "bytes")

Memory size of the NumPy array: 20 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [30]:
import numpy as np
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [45]:
array = np.linspace(0,0,10)
array[4]=1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [55]:
vector2 = np.linspace(10,49,49)
vector2

array([10.    , 10.8125, 11.625 , 12.4375, 13.25  , 14.0625, 14.875 ,
       15.6875, 16.5   , 17.3125, 18.125 , 18.9375, 19.75  , 20.5625,
       21.375 , 22.1875, 23.    , 23.8125, 24.625 , 25.4375, 26.25  ,
       27.0625, 27.875 , 28.6875, 29.5   , 30.3125, 31.125 , 31.9375,
       32.75  , 33.5625, 34.375 , 35.1875, 36.    , 36.8125, 37.625 ,
       38.4375, 39.25  , 40.0625, 40.875 , 41.6875, 42.5   , 43.3125,
       44.125 , 44.9375, 45.75  , 46.5625, 47.375 , 48.1875, 49.    ])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [63]:
arr1 = [1,2,3]
arr1 = np.flip(arr1)
arr1

array([3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [71]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [77]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_elements = arr[arr != 0]
print(non_zero_elements) 

[1 2 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [83]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [101]:
random_array = np.random.rand(3, 3, 3) 
print(random_array)

[[[0.96542706 0.44860492 0.99296217]
  [0.50411298 0.60458055 0.25657101]
  [0.36061324 0.69891537 0.61997184]]

 [[0.29663781 0.89501415 0.68902278]
  [0.60021918 0.25216776 0.68191908]
  [0.38887043 0.05581867 0.62763232]]

 [[0.33738407 0.71136277 0.9896019 ]
  [0.32642237 0.12076238 0.30122191]
  [0.25309845 0.33706474 0.75966824]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [103]:
# Create a 10x10 array with random values
random_array = np.random.rand(10, 10)

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random array:\n", random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Random array:
 [[0.73138368 0.91961149 0.94324817 0.50461846 0.72742461 0.31204957
  0.71872531 0.43714814 0.3454558  0.75257373]
 [0.89208645 0.6019565  0.45368558 0.6279787  0.89366411 0.04498574
  0.06323052 0.6973628  0.19378823 0.9611348 ]
 [0.81074647 0.09925249 0.04826197 0.27688274 0.19483303 0.78660444
  0.26259582 0.47444612 0.673712   0.34992701]
 [0.19408114 0.11405961 0.58849779 0.00181769 0.98994506 0.00497801
  0.64923037 0.88786082 0.39820455 0.5644153 ]
 [0.14281143 0.61134339 0.82918877 0.39789609 0.34263244 0.10226961
  0.42401794 0.59446951 0.81372563 0.17574956]
 [0.97503804 0.94932933 0.84277591 0.70534221 0.12657117 0.06172174
  0.17626413 0.49297586 0.51703457 0.39686931]
 [0.54729556 0.11433998 0.27304614 0.87013248 0.67681355 0.63616556
  0.68804569 0.68478976 0.58230135 0.0292061 ]
 [0.88160239 0.14378976 0.62863795 0.80889757 0.61072196 0.66409101
  0.71665052 0.2377032  0.88140652 0.39451505]
 [0.43363177 0.41125032 0.49682011 0.20926115 0.68464056 0.161636

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [115]:
# Create a random vector of size 30
random_vector = np.random.rand(30)
print("Random vector:", random_vector)
# Calculate the mean value
mean_value = np.mean(random_vector)   
print("Mean value:", mean_value)

SyntaxError: invalid non-printable character U+00A0 (1312522396.py, line 5)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [145]:
import numpy as np

def create_border_array(size):

  arr = np.zeros((size, size), dtype=int)
  arr[0, :] = 1
  arr[-1, :] = 1
  arr[:, 0] = 1
  arr[:, -1] = 1
  return arr

# Example usage:
size = 3
result = create_border_array(size)
print(result)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [151]:
0 * np.nan
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [155]:
arr = np.zeros((5, 5), dtype=int)
arr[1:, :-1] += np.arange(1, 5)
print(arr)

[[0 0 0 0 0]
 [1 2 3 4 0]
 [1 2 3 4 0]
 [1 2 3 4 0]
 [1 2 3 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [157]:
def create_checkerboard(size):
  arr = np.zeros((size, size), dtype=int)
  arr[1::2, ::2] = 1
  arr[::2, 1::2] = 1
  return arr

# Example usage:
checkerboard = create_checkerboard(8)
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [159]:
def find_index(shape, index):
   return np.unravel_index(index, shape)

# Example usage:
array_shape = (6, 7, 8)
element_index = 100
index = find_index(array_shape, element_index)
print(index)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [171]:
def create_checkerboard(size):

  base_pattern = np.array([[0, 1], [1, 0]])
  return np.tile(base_pattern, (size // 2, size // 2))

# Example usage:
checkerboard = create_checkerboard(8)
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [175]:
def normalize_matrix(matrix):

  min_val = np.min(matrix)
  max_val = np.max(matrix)
  return (matrix - min_val) / (max_val - min_val)

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix
normalized_matrix = normalize_matrix(random_matrix)

print("Original matrix:\n", random_matrix)
print("Normalized matrix:\n", normalized_matrix)

Original matrix:
 [[0.39780964 0.23505221 0.1697229  0.69994322 0.55702473]
 [0.54091669 0.65333507 0.18548831 0.89777839 0.03557526]
 [0.6322298  0.06835748 0.73367305 0.37192653 0.84142498]
 [0.3108934  0.80509635 0.18543812 0.9206251  0.32451884]
 [0.57561546 0.60416863 0.54836785 0.52647836 0.87746272]]
Normalized matrix:
 [[0.40928133 0.22538499 0.15157071 0.75065599 0.58917526]
 [0.57097511 0.69799437 0.16938373 0.97418596 0.        ]
 [0.67414796 0.03703996 0.78876664 0.38003653 0.91051338]
 [0.31107642 0.8694664  0.16932702 1.         0.32647154]
 [0.61018055 0.6424422  0.57939402 0.55466153 0.95123169]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [181]:
# Create a custom dtype for RGBA colors
color_dtype = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])

# Example usage:
color = np.array([(255, 0, 0, 255)], dtype=color_dtype)  # Red color with full alpha
print(color)

[(255, 0, 0, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [185]:
# Create a 5x3 matrix
matrix1 = np.random.rand(5, 3)

# Create a 3x2 matrix
matrix2 = np.random.rand(3, 2)

# Multiply the matrices
result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result:\n", result)

Matrix 1:
 [[0.46988926 0.11944411 0.23007989]
 [0.87570931 0.61403622 0.0412867 ]
 [0.87469065 0.22787098 0.62381519]
 [0.55444686 0.0586039  0.43382554]
 [0.30692058 0.57164613 0.16718355]]
Matrix 2:
 [[0.73527586 0.38402837]
 [0.22147966 0.11395541]
 [0.65158244 0.6706382 ]]
Result:
 [[0.52186869 0.34836247]
 [0.80678614 0.43395841]
 [1.10007473 0.78022745]
 [0.70332407 0.51054153]
 [0.46121314 0.29512805]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [189]:
def negate_elements(arr):
 
  mask = (arr > 3) & (arr < 8)
  arr[mask] *= -1

# Example usage:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
negate_elements(arr)
print(arr)  # Output: [1 2 3 -4 -5 -6 -7 -8 9]

[ 1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [195]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [201]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>  # this one 

SyntaxError: invalid syntax (1012071202.py, line 6)

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [203]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\SR Computers\AppData\Local\Temp\ipykernel_10064\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\SR Computers\AppData\Local\Temp\ipykernel_10064\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\SR Computers\AppData\Local\Temp\ipykernel_10064\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [207]:
def round_away_from_zero(arr):
  return np.where(arr >= 0, np.ceil(arr), np.floor(arr))

# Example usage:
arr = np.array([-2.5, -1.2, 0.3, 1.7])
result = round_away_from_zero(arr)
print(result)

[-3. -2.  1.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [213]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

common_elements = np.intersect1d(array1, array2)
print(common_elements)  # Output: [3 4 5]

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [215]:
import warnings

np.seterr(all='ignore')
warnings.simplefilter('ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [5]:
import numpy as np
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\SR Computers\AppData\Local\Temp\ipykernel_1196\3084084354.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [11]:
import datetime
# Get today's date
today = datetime.date.today()

# Calculate yesterday's date
yesterday = today - datetime.timedelta(days=1)

# Calculate tomorrow's date
tomorrow = today + datetime.timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-08-16
Today: 2024-08-17
Tomorrow: 2024-08-18


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [13]:
import pandas as pd

start_date = '2016-07-01'
end_date = '2016-07-31'

july_2016_dates = pd.date_range(start=start_date, end=end_date)

print(july_2016_dates)

DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
               '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
               '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
               '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
               '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
               '2016-07-29', '2016-07-30', '2016-07-31'],
              dtype='datetime64[ns]', freq='D')


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
import numpy as np
def compute_in_place(A, B): 

  # Add A and B, storing the result in B
  np.add(A, B, out=B)

  # Divide A by 2, storing the result in A
  np.(A, 2, out=A)

  # Negate A, storing the result in A
  np.negative(A, out=A)

  # Multiply B and A, storing the result in A
  np.multiply(B, A, out=A)

# Example usage:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
compute_in_place(A, B)
print(A)  # Output: [-7.5 -10.5 -13.5]

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [20]:
# Create a random array of positive numbers
arr = np.random.rand(10) * 100

# Extract integer part using integer division
integer_part = arr // 1
print(integer_part)

[76. 84. 13.  0. 89. 15. 50. 74. 33. 75.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [22]:
# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.arange(5).reshape(5, 1) + np.zeros((5, 5))

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [24]:
import numpy as np

def generate_integers():
  for i in range(10):
    yield i

# Create an array from the generator
array = np.fromiter(generate_integers(), dtype=int)

print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [26]:
# Create a vector with 12 evenly spaced values between 0 and 1 (inclusive)
vector = np.linspace(0, 1, 12)

# Remove the first and last element to exclude 0 and 1
vector = vector[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [28]:
import numpy as np

# Create a random vector of size 10
vector = np.random.rand(10)

# Sort the vector
vector.sort()

print(vector)

[0.01627446 0.17806054 0.35212422 0.3831085  0.40601577 0.41838571
 0.43190065 0.49311376 0.49811336 0.98841692]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [32]:
# No idea

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [34]:
# Create two random arrays
A = np.random.randint(0, 10, 5)
B = np.random.randint(0, 10, 5)

# Check for exact equality (same shape, same elements)
if np.array_equal(A, B):
    print("Arrays are equal")
else:
    print("Arrays are not equal")

Arrays are not equal


#### 43. Make an array immutable (read-only) (★★☆)

In [36]:
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Make the array immutable
arr.flags.writeable = False

# Attempting to modify the array will raise a ValueError
try:
    arr[0] = 10
except ValueError as e:
    print(e)  # Output: array is read-only

assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [38]:
# Generate a random 10x2 matrix of Cartesian coordinates
cartesian_coords = np.random.randn(10, 2)

# Extract x and y coordinates
x, y = cartesian_coords[:, 0], cartesian_coords[:, 1]

# Calculate polar coordinates
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

# Combine r and theta into a polar coordinate matrix
polar_coords = np.column_stack((r, theta))

print(polar_coords)

[[ 0.78789443  1.27649574]
 [ 0.7250568   2.91593822]
 [ 1.37505373 -0.90286162]
 [ 1.22328079 -0.77232844]
 [ 2.42362557 -2.11095924]
 [ 1.84745233 -2.92487461]
 [ 0.93591381  2.78373597]
 [ 2.01343881 -0.20745097]
 [ 1.51635759  3.0378217 ]
 [ 0.13296845 -3.05777217]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [40]:
# Create a random vector of size 10
vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(vector)

# Replace the maximum value with 0
vector[max_index] = 0

print(vector)   


SyntaxError: invalid non-printable character U+00A0 (3200880761.py, line 10)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [42]:
import numpy as np

def create_structured_array(num_points):
  x = np.linspace(0, 1, num_points)
  y = np.linspace(0, 1, num_points)
  X, Y = np.meshgrid(x, y)
  coords = np.vstack([X.ravel(), Y.ravel()]).T
  dtype = [('x', float), ('y', float)]
  return np.array(coords, dtype=dtype)

# Example usage
num_points = 10
structured_array = create_structured_array(num_points)
print(structured_array)

[[(0.        , 0.        ) (0.        , 0.        )]
 [(0.11111111, 0.11111111) (0.        , 0.        )]
 [(0.22222222, 0.22222222) (0.        , 0.        )]
 [(0.33333333, 0.33333333) (0.        , 0.        )]
 [(0.44444444, 0.44444444) (0.        , 0.        )]
 [(0.55555556, 0.55555556) (0.        , 0.        )]
 [(0.66666667, 0.66666667) (0.        , 0.        )]
 [(0.77777778, 0.77777778) (0.        , 0.        )]
 [(0.88888889, 0.88888889) (0.        , 0.        )]
 [(1.        , 1.        ) (0.        , 0.        )]
 [(0.        , 0.        ) (0.11111111, 0.11111111)]
 [(0.11111111, 0.11111111) (0.11111111, 0.11111111)]
 [(0.22222222, 0.22222222) (0.11111111, 0.11111111)]
 [(0.33333333, 0.33333333) (0.11111111, 0.11111111)]
 [(0.44444444, 0.44444444) (0.11111111, 0.11111111)]
 [(0.55555556, 0.55555556) (0.11111111, 0.11111111)]
 [(0.66666667, 0.66666667) (0.11111111, 0.11111111)]
 [(0.77777778, 0.77777778) (0.11111111, 0.11111111)]
 [(0.88888889, 0.88888889) (0.11111111, 0.1111

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [44]:
import numpy as np

def cauchy_matrix(x, y):
  return 1.0 / (x[:, np.newaxis] - y)

# Example usage:
x = np.array([1, 2, 3])
y = np.array([4, 5])

C = cauchy_matrix(x, y)
print(C)

[[-0.33333333 -0.25      ]
 [-0.5        -0.33333333]
 [-1.         -0.5       ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [46]:
import numpy as np

def print_min_max_values():

  for dtype in [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64, np.float16, np.float32, np.float64]:   

    if np.issubdtype(dtype, np.integer):
      info = np.iinfo(dtype)
      print(f"{dtype.__name__}: min={info.min}, max={info.max}")
    else:
      info = np.finfo(dtype)
      print(f"{dtype.__name__}: min={info.min}, max={info.max}, eps={info.eps}")

print_min_max_values()

SyntaxError: invalid non-printable character U+00A0 (2991889878.py, line 6)

#### 49. How to print all the values of an array? (★★☆)

In [48]:
my_array = [1, 2, 3, 4, 5]
print(my_array)  # Output: [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
def find_nearest(array, value):
  array = np.asarray(array)
  idx = (np.abs(array - value)).argmin()
  return array[idx]

# Example usage:
my_array = [3, 8, 2, 9, 5]
value = 6.5

closest_value = find_nearest(my_array, value)
print(closest_value)  # Output: 5

8


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [58]:
def create_position_color_array(num_points):
  dtype = [('position', [('x', float), ('y', float)]),
           ('color', [('r', int), ('g', int), ('b', int)])]
  data = np.zeros(num_points, dtype=dtype)
  return data

# Example usage:
num_points = 5
points_and_colors = create_position_color_array(num_points)
print(points_and_colors)

[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [62]:
def calculate_distances(coordinates):
 
  # Calculate pairwise differences between coordinates
  differences = coordinates[:, np.newaxis, :] - coordinates[np.newaxis, :, :]

  # Calculate squared distances
  squared_distances = np.sum(differences**2, axis=2)

  # Calculate Euclidean distances
  distances = np.sqrt(squared_distances)

  print(distances)
    

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [64]:
def float_to_int_array(float_array):
  int_array = np.zeros_like(float_array, dtype=np.int32)
  int_array = np.rint(float_array).astype(np.int32)  # Round to nearest integer
  return int_array

# Example usage:
float_data = np.array([1.2, 3.4, -2.5], dtype=np.float32)
int_data = float_to_int_array(float_data)
print(int_data)  # Output: [ 1  3 -2]

[ 1  3 -2]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [66]:
def read_data(filename):
  data = []
  with open(filename, 'r') as f:
    for line in f:
      row = [int(x) if x.strip() else np.nan for x in line.split(',')]
      data.append(row)

  return np.array(data)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [68]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for idx, value in np.ndenumerate(arr):
    print(idx, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [70]:
def generate_gaussian_array(shape, sigma=1.0, mean=(0, 0)):
  x, y = np.meshgrid(np.linspace(-1, 1, shape[1]), np.linspace(-1, 1, shape[0]))
  x = (x - mean[0]) * shape[1] / 2
  y = (y - mean[1]) * shape[0] / 2
  z = np.exp(-(x**2 + y**2) / (2 * sigma**2))
  return z

# Example usage:
array_size = (10, 10)
sigma = 0.5
mean = (0.3, 0.7)
gaussian_array = generate_gaussian_array(array_size, sigma, mean)
print(gaussian_array)

[[3.52017005e-100 1.04837492e-088 2.23771871e-079 3.42318410e-072
  3.75310669e-067 2.94908613e-064 1.66080978e-063 6.70329332e-065
  1.93906535e-068 4.02006022e-074]
 [7.60172260e-085 2.26394043e-073 4.83229976e-064 7.39228376e-057
  8.10474366e-052 6.36848059e-049 3.58647879e-048 1.44756008e-049
  4.18736500e-053 8.68122339e-059]
 [1.17651179e-071 3.50388030e-060 7.47890698e-051 1.14409713e-043
  1.25436391e-038 9.85644027e-036 5.55076105e-035 2.24037574e-036
  6.48074724e-040 1.34358516e-045]
 [1.30501781e-060 3.88659617e-049 8.29580030e-040 1.26906262e-032
  1.39137343e-027 1.09330227e-024 6.15705013e-024 2.48508369e-025
  7.18861526e-029 1.49033999e-034]
 [1.03746269e-051 3.08976513e-040 6.59499298e-031 1.00887904e-023
  1.10611366e-018 8.69153134e-016 4.89472997e-015 1.97559113e-016
  5.71480333e-020 1.18479006e-025]
 [5.91104723e-045 1.76042452e-033 3.75756307e-024 5.74818902e-017
  6.30219294e-012 4.95208672e-009 2.78882125e-008 1.12561276e-009
  3.25606623e-013 6.75045962e-019

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [72]:
def random_placement(shape, p, value=1):
  arr = np.zeros(shape, dtype=int)
  indices = np.random.choice(shape[0] * shape[1], p, replace=False)
  arr.flat[indices] = value
  return arr

# Example usage:
shape = (5, 5)
num_elements = 10
array = random_placement(shape, num_elements)
print(array)

[[1 0 1 1 1]
 [0 1 0 0 1]
 [0 0 0 0 0]
 [1 0 1 1 0]
 [1 0 0 0 0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [74]:
import numpy as np

def subtract_row_means(matrix):
  row_means = np.mean(matrix, axis=1, keepdims=True)
  return matrix - row_means

# Example usage:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = subtract_row_means(matrix)
print(result)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [76]:
def sort_by_column(arr, col_index):
  return arr[arr[:, col_index].argsort()]

# Example usage:
data = np.array([[3, 1, 2], [1, 5, 4], [2, 3, 6]])
sorted_data = sort_by_column(data, 1)  # Sort by the second column (index 1)
print(sorted_data)

[[3 1 2]
 [2 3 6]
 [1 5 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [78]:
def has_null_columns(array):
  return np.any(np.isnan(array).all(axis=0))

# Example usage:
array = np.array([[1, 2, np.nan], [3, np.nan, 5], [4, 6, 7]])
has_null_cols = has_null_columns(array)
print(has_null_cols)  # Output: True

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [80]:
def find_nearest(array, value):
  array = np.asarray(array)
  idx = (np.abs(array - value)).argmin()
  return array[idx]

# Example usage:
my_array = np.array([3, 8, 2, 9, 5])
value = 6.5

closest_value = find_nearest(my_array, value)
print(closest_value) 

8


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [84]:
 def compute_sum_with_iterator(arr1, arr2):
  result = np.zeros((1, 1))
  for i in range(3):
    result[0, 0] += arr1[0, i] + arr2[i, 0]
  return result

# Example usage:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4], [5], [6]])
sum_result = compute_sum_with_iterator(arr1, arr2)
print(sum_result)

[[21.]]


#### 63. Create an array class that has a name attribute (★★☆)

In [86]:
class NamedArray:
  def __init__(self, data, name):
    self.data = np.array(data)
    self.name = name

  def __repr__(self):
    return f"NamedArray('{self.name}', {self.data})"

  def __str__(self):
    return f"{self.name}:\n{self.data}"

# Example usage:
array_data = [[1, 2, 3], [4, 5, 6]]
named_array = NamedArray(array_data, "My Array")
print(named_array)

My Array:
[[1 2 3]
 [4 5 6]]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [88]:
def accumulate_elements(X, I, F):
  F[I] += X[I]
  return F

# Example usage:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 2, 4])
F = np.zeros(5)

F = accumulate_elements(X, I, F)
print(F)

[1. 0. 3. 0. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
import numpy as np

def count_unique_colors(image):

  # Reshape image into a 2D array of pixels
  flattened_image = image.reshape(-1, 3)

  # Find unique colors
  unique_colors = np.unique(flattened_image, axis=0)

  return len(unique_colors)

# Example usage:
import cv2  # Or any image loading library

# Load an image
img = cv2.imread('your_image.jpg')

# Convert to uint8 if necessary
img = img.astype(np.uint8)

num_colors = count_unique_colors(img)
print(num_colors)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [93]:
def sum_over_last_two_axes(array):
  return np.sum(array, axis=(-2, -1))

# Example usage:
array = np.random.rand(2, 3, 4, 5)
result = sum_over_last_two_axes(array)
print(result.shape)  # Output: (2, 3)

(2, 3)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [95]:
def compute_subset_means(D, S):
  unique_subsets = np.unique(S)
  subset_means = []
  for s in unique_subsets:
    subset_indices = np.where(S == s)[0]
    subset_mean = np.mean(D[subset_indices])
    subset_means.append(subset_mean)
  return subset_means

# Example usage:
D = np.array([1, 2, 3, 4, 5, 6])
S = np.array([0, 0, 1, 1, 2, 2])
means = compute_subset_means(D, S)
print(means)

[1.5, 3.5, 5.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [97]:
def diagonal_of_dot_product(A, B):
  dot_product = np.dot(A, B)
  diagonal = np.diag(dot_product)
  return diagonal

# Example usage:
A = np.random.rand(3, 4)
B = np.random.rand(4, 3)
diagonal_result = diagonal_of_dot_product(A, B)
print(diagonal_result)

[1.2059158  0.55292017 1.15543865]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [99]:
def interleave_zeros(vector):
  result = np.zeros(len(vector) * 4 - 3)  # Calculate the length of the output vector
  result[::4] = vector  # Assign original values to every fourth position
  return result

# Example usage:
vector = np.array([1, 2, 3, 4, 5])
interleaved_vector = interleave_zeros(vector)
print(interleaved_vector)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [101]:
def multiply_arrays(array1, array2):
  return array1 * array2[:, :, np.newaxis]

# Example usage:
array1 = np.random.rand(5, 5, 3)
array2 = np.random.rand(5, 5)
result = multiply_arrays(array1, array2)
print(result.shape)  # Output: (5, 5, 3)

(5, 5, 3)


#### 72. How to swap two rows of an array? (★★★)

In [103]:
def swap_rows(arr, row1, row2):
  arr[[row1, row2]] = arr[[row2, row1]]
  return arr

# Example usage:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array = swap_rows(array, 0, 2)
print(array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [105]:
import numpy as np

def find_unique_line_segments(triangles):
  """Finds unique line segments from a set of triangles.

  Args:
    triangles: A NumPy array of shape (n, 3) where each row represents a triangle.

  Returns:
    A NumPy array of shape (m, 2) where each row represents a unique line segment.
  """

  # Create all possible edges for each triangle
  edges = np.roll(triangles.repeat(2, axis=1), -1, axis=1)

  # Sort each edge to ensure consistency (e.g., (0, 1) and (1, 0) are considered the same)
  edges = np.sort(edges, axis=1)

  # Find unique edges
  unique_edges = np.unique(edges, axis=0)

  return unique_edges

# Example usage:
triangles = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4]])
unique_segments = find_unique_line_segments(triangles)
print(unique_segments)

[[0 0 1 1 2 2]
 [1 1 2 2 3 3]
 [2 2 3 3 4 4]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [107]:
def reconstruct_array(C):
  """Reconstructs an array from its bincount.

  Args:
    C: The bincount array.

  Returns:
    The reconstructed array.
  """

  return np.repeat(np.arange(len(C)), C)

# Example usage:
C = np.array([0, 2, 1, 3])
A = reconstruct_array(C)
print(A)

[1 1 2 3 3 3]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [109]:
def sliding_window_average(array, window_size):
  """Computes the average of elements within a sliding window.

  Args:
    array: The input array.
    window_size: The size of the sliding window.

  Returns:
    A NumPy array containing the averages.
  """

  cumsum = np.cumsum(array)
  cumsum[window_size:] = cumsum[window_size:] - cumsum[:-window_size]
  return cumsum[window_size - 1:] / window_size

# Example usage:
array = np.array([1, 3, 5, 7, 9, 11])
window_size = 3
averages = sliding_window_average(array, window_size)
print(averages)

[3. 5. 7. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [111]:
import numpy as np

def create_shifted_array(Z, window_size):
  return np.lib.stride_tricks.sliding_window_view(Z, window_size)

# Example usage:
Z = np.array([1, 2, 3, 4, 5, 6, 7])
window_size = 3
result = create_shifted_array(Z, window_size)
print(result)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [113]:
my_bool = True
negated_bool = not my_bool  # negated_bool will be False

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [115]:
def point_to_line_distance(P0, P1, p):
  """Computes the distance from a point to multiple lines.

  Args:
    P0: Array of starting points of the lines (shape: N, 2).
    P1: Array of ending points of the lines (shape: N, 2).
    p: The point to calculate distances from (shape: 2).

  Returns:
    An array of distances, one for each line.
  """

  # Calculate line vectors
  line_vecs = P1 - P0

  # Calculate vectors from P0 to p
  p0_to_p = p - P0

  # Calculate dot products
  dot_products = np.sum(p0_to_p * line_vecs, axis=1)

  # Calculate line lengths
  line_lengths = np.linalg.norm(line_vecs, axis=1)

  # Calculate parameters
  u = dot_products / line_lengths**2

  # Calculate closest points on lines
  closest_points = P0 + u[:, np.newaxis] * line_vecs

  # Calculate distances
  distances = np.linalg.norm(closest_points - p, axis=1)

  return distances

# Example usage:
P0 = np.array([[0, 0], [1, 1], [2, 0]])
P1 = np.array([[1, 1], [2, 0], [3, 1]])
p = np.array([2, 2])
distances = point_to_line_distance(P0, P1, p)
print(distances)

[6.28036983e-16 1.41421356e+00 1.41421356e+00]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [117]:
def point_to_lines_distance(P0, P1, P):
  """Computes distances from multiple points to multiple lines.

  Args:
    P0: Array of starting points of the lines (shape: N, 2).
    P1: Array of ending points of the lines (shape: N, 2).
    P: Array of points to calculate distances from (shape: M, 2).

  Returns:
    A matrix of distances with shape (M, N).
  """

  # Calculate line vectors
  line_vecs = P1 - P0

  # Calculate vectors from P0 to points in P
  P0_to_P = P[:, np.newaxis, :] - P0[np.newaxis, :, :]

  # Calculate dot products
  dot_products = np.sum(P0_to_P * line_vecs, axis=2)

  # Calculate line lengths
  line_lengths = np.linalg.norm(line_vecs, axis=1)

  # Calculate parameters
  u = dot_products / line_lengths**2

  # Calculate closest points on lines
  closest_points = P0 + u[:, :, np.newaxis] * line_vecs

  # Calculate distances
  distances = np.linalg.norm(closest_points - P[:, np.newaxis, :], axis=2)

  return distances

# Example usage:
P0 = np.random.rand(10, 2)
P1 = np.random.rand(10, 2)
P = np.random.rand(5, 2)
distances = point_to_lines_distance(P0, P1, P)
print(distances.shape)  # Output: (5, 10)

(5, 10)


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [119]:
def extract_subarray(array, shape, center, fill_value=0):
  """Extracts a subarray with a fixed shape centered on a given element.

  Args:
    array: The input array.
    shape: The desired shape of the subarray.
    center: The coordinates of the center element in the array.
    fill_value: The value to use for padding.

  Returns:
    The extracted subarray.
  """

  array_shape = np.array(array.shape)
  subarray_shape = np.array(shape)
  start = np.maximum(center - subarray_shape // 2, 0)
  end = np.minimum(center + subarray_shape // 2, array_shape)

  slices = tuple(slice(s, e) for s, e in zip(start, end))
  subarray = array[slices]

  # Padding if necessary
  pad_width = []
  for i in range(len(shape)):
    pad_width.append((max(0, -start[i]), max(0, end[i] - array_shape[i])))
  subarray = np.pad(subarray, pad_width, mode='constant', constant_values=fill_value)

  return subarray

# Example usage:
array = np.arange(25).reshape(5, 5)
shape = (3, 3)
center = (2, 2)
fill_value = -1
subarray = extract_subarray(array, shape, center, fill_value)
print(subarray)

[[ 6  7]
 [11 12]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [121]:
import numpy as np

def create_shifted_array(Z, window_size):
  """Creates a 2D array with shifted rows from a 1D array.

  Args:
    Z: The input 1D array.
    window_size: The size of each row in the output array.

  Returns:
    The resulting 2D array.
  """

  return np.lib.stride_tricks.sliding_window_view(Z, window_size)

# Example usage:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
window_size = 4
result = create_shifted_array(Z, window_size)
print(result)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [123]:
# Create a sample matrix
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

# Calculate the rank
rank = np.linalg.matrix_rank(A)

print("Rank of the matrix:", rank)

Rank of the matrix: 2


#### 83. How to find the most frequent value in an array?

In [125]:
def find_most_frequent(arr):
  """Finds the most frequent value in a NumPy array.

  Args:
    arr: The input NumPy array.

  Returns:
    The most frequent value in the array.
  """

  counts = np.bincount(arr)
  return np.argmax(counts)

# Example usage:
arr = np.array([1, 2, 2, 3, 2, 4, 5, 2, 2])
most_frequent = find_most_frequent(arr)
print(most_frequent)  # Output: 2

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [127]:
def extract_blocks(arr, block_size):
  """Extracts contiguous blocks from a 2D array.

  Args:
    arr: The input 2D array.
    block_size: The size of the blocks to extract.

  Returns:
    A 4D array containing the extracted blocks.
  """

  shape = (arr.shape[0] - block_size + 1, arr.shape[1] - block_size + 1, block_size, block_size)
  strides = arr.strides + arr.strides
  return np.lib.stride_tricks.as_strided(arr, shape=shape, strides=strides)

# Example usage:
matrix = np.random.randint(0, 10, size=(10, 10))
blocks = extract_blocks(matrix, 3)
print(blocks.shape)  # Output: (8, 8, 3, 3)

(8, 8, 3, 3)


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [129]:
class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        if not np.allclose(obj, obj.T):
            raise ValueError("Input array is not symmetric")
        return obj

    def __setitem__(self, key, value):
        i, j = key
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)

# Example usage:
data = np.array([[1, 2, 3],
                 [2, 4, 5],
                 [3, 5, 6]])

symmetric_array = SymmetricArray(data)
symmetric_array[1, 2] = 7  # This will also set symmetric_array[2, 1] to 7

print(symmetric_array)

[[1 2 3]
 [2 4 7]
 [3 7 6]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)