In [22]:
import numpy as np
ary8 = np.array([[111,222,333],[21,22,23],[31,32,33]])
print(ary8[1:,1:])
print(ary8.max())
print(ary8.min())
print(ary8.argmax())

[[22 23]
 [32 33]]
333
21
2


In [24]:
ary9 = np.array([0, np.pi/2, np.pi])
print(ary9)

[0.         1.57079633 3.14159265]


In [39]:
import numpy as np
u = np.array([21,22])
v = np.array([1,2])
a = np.dot(u,v)
a
ar = np.concatenate((u,v))
ar
np.linspace(3,-3,54)

array([ 3.        ,  2.88679245,  2.77358491,  2.66037736,  2.54716981,
        2.43396226,  2.32075472,  2.20754717,  2.09433962,  1.98113208,
        1.86792453,  1.75471698,  1.64150943,  1.52830189,  1.41509434,
        1.30188679,  1.18867925,  1.0754717 ,  0.96226415,  0.8490566 ,
        0.73584906,  0.62264151,  0.50943396,  0.39622642,  0.28301887,
        0.16981132,  0.05660377, -0.05660377, -0.16981132, -0.28301887,
       -0.39622642, -0.50943396, -0.62264151, -0.73584906, -0.8490566 ,
       -0.96226415, -1.0754717 , -1.18867925, -1.30188679, -1.41509434,
       -1.52830189, -1.64150943, -1.75471698, -1.86792453, -1.98113208,
       -2.09433962, -2.20754717, -2.32075472, -2.43396226, -2.54716981,
       -2.66037736, -2.77358491, -2.88679245, -3.        ])

In [41]:
x=np.linspace(0,2*np.pi,num=100)
print(x)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520